function HP3245A_GPIB_set_A(source,frequency,amplitude,type)
%this program is written by Martijn Schouten
%for questions email: m.schouten-1@alumnus.utwente.nl
%The program is written for use with the GPIB-USB-B converter 
%and the agilent 54622D scope.
%Before using this program install the NI488-2 driver.
%written using Matlab R2017a

%to find the primary GPIB adress of the scope run tmtool
%scan for GPIB cards and scan for GPIB devices. 

%input parameters:
%source: the GPIB object generated by HP3245A_GPIB_init
%frequency: the frequency of the to be gerenated wavefrom in Hz
%amplitude: the amplitude of the to be gerenated waveform in V or A
%waveform: the type of waveform to be generated options are:
%               'ACV' or 'ACI': voltage or current sine wave
%               'SQV' or 'SQI': voltage or current square wave
%               'RPV' or 'RPI': voltage or current ramp

fprintf(source,['FREQ ',num2str(frequency)]);
fprintf(source,['APPLY ',type,' ',num2str(amplitude)]);
